services:
  app:
    image: ghcr.io/guhzoide/rentalmanager:${IMAGE_TAG:-rentalManger-latest-amd64}
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://admin:123@postgresql:5432/dbdev?schema=public
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
    ports:
      - "${APP_PORT:-3001}:3001"
    networks:
      - proxy-localhost-network

networks:
  proxy-localhost-network:
    external: true