version: '3.8'

services:
  mongodb:
    image: bitnami/mongodb:7.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_HOST=localhost
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
