export const domains = {
    ISOFlag: [
        { value: 'A', label: 'Ativo' },
        { value: 'I', label: 'Inativo' },
    ],
    ISOSN: [
        { value: 'S', label: 'Sim' },
        { value: 'N', label: 'Não' },
    ],
    ISOSexo: [
        { value: 'M', label: 'Masculino' },
        { value: 'F', label: 'Feminino' },
        { value: 'N', label: 'Não informado' },
    ],
    ISOLicTipo: [
        { value: '0', label: 'Inexistente' },
        { value: '1', label: 'Concorrente' },
        { value: '2', label: 'Demonstracao' },
        { value: '3', label: 'Simultanea' },
        { value: '4', label: 'On_demand' },
        { value: '5', label: 'Treinamento' },
    ],
    ISOTipoUsuario: [
        { value: '0', label: 'Normal' },
        { value: '1', label: 'Atendente' },
        { value: '2', label: 'Supervisor' },
        { value: '9', label: 'Master' },
    ],
    ISOIdioma: [
        { value: 'pt', label: 'Português' },
        { value: 'en', label: 'Inglês' },
        { value: 'es', label: 'Espanhol' },
        { value: 'it', label: 'Italiano' },
    ],
    ISOTablesDeleteAllowed: [
        { value: 'ISOSesModulo', label: 'ISOSesModulo' },
        { value: 'ISOSessao', label: 'ISOSessao' },
    ],
    ISOModulo: [
        { value: "AAGE", label: "Atendente - Agenda", color: 'red' },
        { value: "AANL", label: "Atendente - Analítico", color: 'blue' },
        { value: "AAPP", label: "Atendente - APP", color: 'green' },
        { value: "ACAM", label: "Atendente - Campanhas", color: 'yellow' },
        { value: "ACHQ", label: "Check in - Check out", color: 'purple' },
        { value: "ACHT", label: "Atendente - Chat", color: 'orange' },
        { value: "ACOR", label: "Atendente - Correios", color: 'pink' },
        { value: "ACTR", label: "Atendente - Contratos", color: 'brown' },
        { value: "AESA", label: "Atendente - Email entrada SAC", color: 'gray' },
        { value: "AEVN", label: "Atendente - Eventos", color: 'red' },
        { value: "AGER", label: "Atendente - Cadastros gerais", color: 'blue' },
        { value: "AGOO", label: "Atendente - Google Agenda", color: 'green' },
        { value: "AHST", label: "Atendente - Histórico", color: 'red' },
        { value: "AISO", label: "Atendente - isoCRM Web", color: 'blue' },
        { value: "ALJV", label: "Atendente - Loja virtual", color: 'green' },
        { value: "AMAN", label: "iso - Manutenção WS", color: 'yellow' },
        { value: "AMCL", label: "Atendente - Mercado Livre", color: 'purple' },
        { value: "AMET", label: "Atendente - Metas", color: 'orange' },
        { value: "APES", label: "Atendente - Pesquisa", color: 'pink' },
        { value: "ASAC", label: "Atendente - Serviço de atendimento ao cliente", color: 'brown' },
        { value: "ASIT", label: "Atendente - Site", color: 'gray' },
        { value: "AVEN", label: "Atendente - Vendas", color: 'red' },
        { value: "AWFL", label: "Atendente - Workflow", color: 'blue' },
        { value: "RECO", label: "RecoPlanner", color: 'green' },
        { value: "SAGE", label: "Supervisor - Agenda", color: 'red' },
        { value: "SATV", label: "Supervisor - Atividades", color: 'blue' },
        { value: "SCAM", label: "Supervisor - Campanhas", color: 'green' },
        { value: "SCHT", label: "Supervisor - Chat", color: 'yellow' },
        { value: "SCTR", label: "Supervisor - Contratos", color: 'purple' },
        { value: "SESA", label: "Supervisor - Email de entrada SAC", color: 'orange' },
        { value: "SEVN", label: "Supervisor - Eventos", color: 'pink' },
        { value: "SGER", label: "Supervisor - Cadastros básicos e gerais", color: 'brown' },
        { value: "SLJV", label: "Supervisor - Loja virtual", color: 'gray' },
        { value: "SMET", label: "Supervisor - Metas", color: 'red' },
        { value: "SPES", label: "Supervisor - Pesquisa", color: 'blue' },
        { value: "SSAC", label: "Supervisor - Serviço de atendimento ao cliente", color: 'green' },
        { value: "SSEL", label: "Supervisor - Seleção e prospecção", color: 'yellow' },
        { value: "SSIT", label: "Supervisor - Site", color: 'purple' },
        { value: "SVEN", label: "Supervisor - Vendas", color: 'orange' },
        { value: "SWFL", label: "Supervisor - Workflow", color: 'pink' },
        { value: "TVEN", label: "isoCRM Tablet - Vendas", color: 'brown' }
    ],
    ISOModuloPerfil: [
        { value: "AGE", label: "Agenda", color: 'red' },
        { value: "CAM", label: "Campanha", color: 'blue' },
        { value: "ENT", label: "Entidade", color: 'green' },
        { value: "SAC", label: "SAC", color: 'yellow' },
        { value: "OS", label: "OS", color: 'purple' },
        { value: "VEN", label: "Venda", color: 'orange' },
        { value: "WFL", label: "Workflow", color: 'pink' },
        { value: "PES", label: "Pesquisa", color: 'brown' },
        { value: "OMC", label: "Omnichannel Chat", color: 'gray' },
        { value: "OME", label: "Omnichannel E-mail", color: 'red' },
        { value: "OML", label: "Omnichannel Call", color: 'blue' },
    ],
    ISOPapel: [
        { value: 'Cliente', label: 'Cliente' },
        { value: 'Fornecedor', label: 'Fornecedor' },
        { value: 'Parceiro', label: 'Parceiro' },
        { value: 'Prestador', label: 'Prestador' },
        { value: 'Responsavel', label: 'Responsavel' },
        { value: 'Unidade', label: 'Unidade' },
        { value: 'Usuario', label: 'Usuário' },
    ],
    ISOEntSituacao: [
        { value: '9', label: 'Cancelado' },
        { value: '2', label: 'Concluído' },
        { value: '3', label: 'Encaminhar para workflow' },
        { value: '1', label: 'Pendente' },
    ],
    ISOPvPedSit_Situacao: [
        { value: '0', label: 'Selecione' },
        { value: '1', label: 'Aberto' },
        { value: '2', label: 'Em aprovação' },
        { value: '3', label: 'Em produção' },
        { value: '4', label: 'Avaliação de cadastro' },
        { value: '5', label: 'Avaliação de pedido' },
        { value: '6', label: 'Faturado parcial' },
        { value: '7', label: 'Faturado total' },
        { value: '8', label: 'Cotação' },
        { value: '9', label: 'Cancelado' },
        { value: '10', label: 'Encaminhar para workflow' },
        { value: '11', label: 'Aprovação de cotas' },
        { value: '12', label: 'Suspenso' },
        { value: '13', label: 'Separação - Destinação' },
        { value: '14', label: 'Separação - Quantidade' },
        { value: '15', label: 'Separação - Destinação (aguardando divisão)' },
        { value: '16', label: 'Separação - Quantidade (aguardando divisão)' },
        { value: '17', label: 'Pendência' },
        { value: '18', label: 'Pendência agrupamento' },
        { value: '19', label: 'Separação' },
        { value: '20', label: 'Separação - Tipo pedido' },
        { value: '21', label: 'Separação - Quantidade total' }
    ],

    ISOPeCntPgt_Forma: [
        { value: 'Bol', label: 'Boleto' },
        { value: 'Car', label: 'Cartão' },
        { value: 'Che', label: 'Cheque' },
        { value: 'Dep', label: 'Depósito' },
        { value: 'Din', label: 'Dinheiro' },
        { value: 'Fin', label: 'Financiamento' },
        { value: 'Inf', label: 'Infocards' },
        { value: 'Ord', label: 'Ordem de Crédito' }
    ],
    ISOTipoTurno: [
        { value: 'NOR', label: 'Normal' },
        { value: 'EXT', label: 'Extraordinário' },
    ],
    ISODiaSemana: [
        { value: '1', label: 'Domingo' },
        { value: '2', label: 'Segunda' },
        { value: '3', label: 'Terça' },
        { value: '4', label: 'Quarta' },
        { value: '5', label: 'Quinta' },
        { value: '6', label: 'Sexta' },
        { value: '7', label: 'Sábado' },
        { value: '0', label: 'Selecionar' },
    ],
    ISOTipoEcontact: [
        { value: 'cce', label: 'Comunicador c/ validaçãao e-mail' },
        { value: 'cse', label: 'Comunicador s/ validaçãao e-mail' },
        { value: 'email', label: 'e-mail' },
        { value: 'link', label: 'Link' },
        { value: 'outros', label: 'outros' },
        { value: 'web', label: 'web site' }
    ],
    ISOTipoOperacao: [
        { value: 'ALT', label: 'Cadastro alterado' },
        { value: 'INC', label: 'Novo cadastro' },
        { value: 'ENV', label: 'Cadastro enviado' },
        { value: 'BPC', label: 'Controle ERP (BPC)' },
        { value: 'ERR', label: 'Erro de integração' },
    ],
    ISOMkCmpTipo: [
        { value: "0", label: "Automática" },
        { value: "1", label: "Lista" },
        { value: "2", label: "Jogos" },
        { value: "3", label: "Pesquisa" }
    ],
    ISOMkCntSituacaoTabulada: [
        { value: "0", label: "Encaminhado" },
        { value: "1", label: "Concluído" },
        { value: "2", label: "Em atendimento" },
        { value: "3", label: "Encaminhar para WorkFlow" },
        { value: "9", label: "Cancelado" }
    ],
    ISOTipoContaEmail: [
        { value: "F", label: "FORMULARIO" },
        { value: "I", label: "IMAP" },
        { value: "P", label: "POP" },
        { value: "S", label: "SMTP" }
    ],
    ISOSASituacao: [
        { value: '1', label: 'Aberto' },
        { value: '2', label: 'Fechado' },
        { value: '3', label: 'Encaminhar para work flow' },
        { value: '9', label: 'Cancelado' }
    ],
    ISOAgeSituacao: [
        { value: "0", label: "Selecione" },
        { value: "1", label: "Cancelado" },
        { value: "2", label: "Concluído" },
        { value: "3", label: "Agendamento confirmado" },
        { value: "4", label: "Agendamento pendente" }
    ],
    ISOChatAtendente: [
        { value: "1", label: "Disponível" },
        { value: "2", label: "Indisponível" },
    ],
    ISOCanal: [
        { value: "1", label: "Telefone" },
        { value: "2", label: "e-mail" },
        { value: "3", label: "FAX" },
        { value: "4", label: "Chat" },
        { value: "5", label: "Pessoal" },
        { value: "6", label: "Carta" }
    ],
    ISOChatOcultar: [
        { value: "0", label: "Não mostrar" },
        { value: "1", label: "Mostrar" },
        { value: "2", label: "Obrigatório" }
    ],
    ISOChatSituacao: [
        { value: "0", label: "Em espera" },
        { value: "1", label: "Em atendimento" },
        { value: "2", label: "Encerrado" },
        { value: "3", label: "Cliente saiu" },
        { value: "4", label: "Em atendimento bot" },
        { value: "5", label: "Em espera (transferência)" },
        { value: "9", label: "Retorna Espera" }
    ]
}